"""empty message

Revision ID: a559758b0e1e
Revises: d7be77f6b537
Create Date: 2020-04-11 14:23:12.936833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a559758b0e1e'
down_revision = 'd7be77f6b537'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('homework_prob',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('prob_id', sa.Integer(), nullable=True),
    sa.Column('hw_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hw_id'], ['homework.hw_id'], ),
    sa.ForeignKeyConstraint(['prob_id'], ['problem.prob_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('homework', sa.Column('content', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('homework', 'content')
    op.drop_table('homework_prob')
    # ### end Alembic commands ###
