"""empty message

Revision ID: dc9ee7b1894b
Revises: ff07f4fd5e7f
Create Date: 2020-05-04 10:28:45.017465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc9ee7b1894b'
down_revision = 'ff07f4fd5e7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_comment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('desc', sa.Text(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('com_id', sa.Integer(), nullable=True),
    sa.Column('reporter_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['com_id'], ['comment.com_id'], ),
    sa.ForeignKeyConstraint(['reporter_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report_comment')
    # ### end Alembic commands ###
