"""empty message

Revision ID: ff07f4fd5e7f
Revises: 3b7c7d3118ad
Create Date: 2020-05-01 14:31:46.120961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff07f4fd5e7f'
down_revision = '3b7c7d3118ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hw_score',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hw_id', sa.Integer(), nullable=True),
    sa.Column('stu_id', sa.String(length=100), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hw_id'], ['homework.hw_id'], ),
    sa.ForeignKeyConstraint(['stu_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hw_prob_score',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hw_prob_id', sa.Integer(), nullable=True),
    sa.Column('stu_id', sa.String(length=100), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('submit', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hw_prob_id'], ['homework_prob.id'], ),
    sa.ForeignKeyConstraint(['stu_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hw_prob_score')
    op.drop_table('hw_score')
    # ### end Alembic commands ###
